modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    ordering = "NONE"
    side = "BOTH"
    versionRange = "[45.0.0,50.0.0)"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "1.20.1"